# Generated by Django 5.1.5 on 2025-02-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_name_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('auto', 'Авто'), ('electronics', 'Електроніка'), ('home_garden', 'Дім і сад'), ('clothing', 'Одяг'), ('real_estate', 'Нерухомість'), ('baby_world', 'Дитячий світ'), ('gaming', 'Для геймерів')], default='auto', max_length=40),
        ),
    ]
