# Generated by Django 5.1.5 on 2025-02-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Авто', 'Авто'), ('Електроніка', 'Електроніка'), ('Дім і сад', 'Дім і сад'), ('Одяг', 'Одяг'), ('Нерухомість', 'Нерухомість'), ('Дитячий світ', 'Дитячий світ'), ('Для геймерів', 'Для геймерів')], max_length=40),
        ),
    ]
