# Generated by Django 5.1.4 on 2025-02-14 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Авто', 'Авто'), ('Електроніка', 'Електроніка'), ('Дім сад', 'Дім сад'), ('Одяг', 'Одяг'), ('Нерухомість', 'Нерухомість'), ('Дитячий світ', 'Дитячий світ'), ('Для геймерів', 'Для геймерів'), ('Інше', 'Інше')], max_length=40),
        ),
    ]
