# Generated by Django 5.1.4 on 2025-02-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_author_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Авто', 'Авто'), ('Електроніка', 'Електроніка'), ('Дім сад', 'Дім сад'), ('Одяг', 'Одяг'), ('Нерухомість', 'Нерухомість'), ('Дитячий світ', 'Дитячий світ'), ('тварини', 'Тварини'), ('Інше', 'Інше')], max_length=40),
        ),
    ]
