# Generated by Django 5.1.5 on 2025-02-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Auto', 'Auto'), ('Electronics', 'Electronics'), ('Home/Garden', 'Home/Garden'), ('Clothes', 'Clothes'), ('Realty', 'Realty'), ('Toys', 'Toys'), ('Animals', 'Animals'), ('Other', 'Other')], max_length=40),
        ),
    ]
